"""Cascade

Revision ID: 3fa583d4230f
Revises: 3ade5b92c6ba
Create Date: 2026-09-26 18:23:55.071594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa583d4230f'
down_revision: Union[str, Sequence[str], None] = '3ade5b92c6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sales_follow_ups_lead_id_fkey'), 'sales_follow_ups', type_='foreignkey')
    op.create_foreign_key(None, 'sales_follow_ups', 'sales_leads', ['lead_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_follow_ups', type_='foreignkey')
    op.create_foreign_key(op.f('sales_follow_ups_lead_id_fkey'), 'sales_follow_ups', 'sales_leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###
