"""add sales and tech tables

Revision ID: 8c603843eb59
Revises: 0c2fc1da4d8f
Create Date: 2026-09-24 15:29:51.219342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c603843eb59'
down_revision: Union[str, Sequence[str], None] = '0c2fc1da4d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_leads_execution_id'), 'sales_leads', ['execution_id'], unique=False)
    op.create_table('tech_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_tickets_execution_id'), 'tech_tickets', ['execution_id'], unique=False)
    op.create_table('sales_follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_follow_ups_execution_id'), 'sales_follow_ups', ['execution_id'], unique=False)
    op.create_index(op.f('ix_sales_follow_ups_lead_id'), 'sales_follow_ups', ['lead_id'], unique=False)
    op.create_table('tech_fixes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('proposed_fix', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tech_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_fixes_execution_id'), 'tech_fixes', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tech_fixes_ticket_id'), 'tech_fixes', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_fixes_ticket_id'), table_name='tech_fixes')
    op.drop_index(op.f('ix_tech_fixes_execution_id'), table_name='tech_fixes')
    op.drop_table('tech_fixes')
    op.drop_index(op.f('ix_sales_follow_ups_lead_id'), table_name='sales_follow_ups')
    op.drop_index(op.f('ix_sales_follow_ups_execution_id'), table_name='sales_follow_ups')
    op.drop_table('sales_follow_ups')
    op.drop_index(op.f('ix_tech_tickets_execution_id'), table_name='tech_tickets')
    op.drop_table('tech_tickets')
    op.drop_index(op.f('ix_sales_leads_execution_id'), table_name='sales_leads')
    op.drop_table('sales_leads')
    # ### end Alembic commands ###
